<Container>:
    TextInput:
        size_hint: .9, .05
        pos_hint: {'center_x':.5, 'top':.95}
        multiline: False
       # size: , 200
        hint_text:"Найменування"



    TextInput:
        size_hint: .9, .05
        pos_hint: {'center_x':.5, 'top':.85}
        multiline: False
        hint_text:"Артикул"

    TextInput:
        size_hint: .9, .05
        pos_hint: {'center_x':.5, 'top':.75}
        multiline: False
        hint_text:"Штрих код"

